# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jasonkhadka.github.io
title: Jason Khadka
email: jasonkhadka33@gmail.com
author: Jason Khadka
description: > # "Write an awesome description for your new site here. 
  Jason Khadka is a PhD student at Max Planck Institute for Dynamics and Self-Organisation. He is working on developing a 3D mechanical model for plant tissue growth.
copyright: 'Copyright &copy; 2018 Jason Khadka. All Rights Reserved.'
credits: 'Built upon open source.<br><a href="https://jekyllrb.com//">Jekyll</a> . <a href="http://startbootstrap.com/">Start Bootstrap</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: twitter
  #  url: https://twitter.com/SBootstrap
  - title: email
    url: mailto:jasonkhadka33@gmail.com
  - title: github
    url: https://github.com/jasonkhadka
  - title: linkedin
    url: https://linkedin.com/in/khadka
  